"""init

Revision ID: cd230be47003
Revises: 
Create Date: 2023-09-25 20:03:31.905873

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cd230be47003'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'secrets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('secret_key', sa.String(length=36), nullable=True),
        sa.Column('hash_secret_phrase', sa.String(length=64), nullable=True),
        sa.Column('hash_message', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secrets')
    # ### end Alembic commands ###
